#Requires -Version 5.1
<#
  build.ps1 - bundle src\ into a single dist\Sel01Tweaker.ps1 for one-liner use:
      & ([scriptblock]::Create((irm <url>/Sel01Tweaker.ps1))) -Profile Gaming

  Inserts lib + modules at the #__SEL01TWEAKER_BUNDLE_INSERT__ marker so the entry's
  param() block stays the first statement in the file.
#>
[CmdletBinding()]
param([string]$OutFile = (Join-Path $PSScriptRoot 'dist\Sel01Tweaker.ps1'))

$src    = Join-Path $PSScriptRoot 'src'
$marker = '#__SEL01TWEAKER_BUNDLE_INSERT__'

# Order: shared libs first, then numbered modules.
$parts = @(
    (Join-Path $src 'lib\Common.ps1'),
    (Join-Path $src 'lib\Backup.ps1')
) + (Get-ChildItem (Join-Path $src 'modules') -Filter '*.ps1' | Sort-Object Name | ForEach-Object FullName)

$bundle = [System.Text.StringBuilder]::new()
foreach ($p in $parts) {
    [void]$bundle.AppendLine("# ----- bundled: $(Split-Path $p -Leaf) -----")
    [void]$bundle.AppendLine((Get-Content -Path $p -Raw))
    [void]$bundle.AppendLine('')
}

$entry = Get-Content -Path (Join-Path $src 'Sel01Tweaker.ps1') -Raw
if (-not $entry.Contains($marker)) { throw "Marker $marker not found in src\Sel01Tweaker.ps1" }

$header = @"
# ============================================================================
#  Sel01Tweaker - bundled distribution (generated by build.ps1; do not edit by hand)
#  One-click Windows 11 debloat + performance optimizer.
#  Source: src\  |  Run: .\Sel01Tweaker.ps1 -Profile Gaming   (auto-elevates)
# ============================================================================
"@

$final = $entry.Replace($marker, ($header + "`r`n" + $bundle.ToString()))

$outDir = Split-Path $OutFile -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
Set-Content -Path $OutFile -Value $final -Encoding UTF8

# Syntax-validate the generated file before declaring success.
$errors = $null
[void][System.Management.Automation.Language.Parser]::ParseFile($OutFile, [ref]$null, [ref]$errors)
if ($errors -and $errors.Count) {
    Write-Host "Bundle has syntax errors:" -ForegroundColor Red
    $errors | ForEach-Object { Write-Host "  $($_.Message) (line $($_.Extent.StartLineNumber))" -ForegroundColor Red }
    exit 1
}

$kb = [math]::Round((Get-Item $OutFile).Length / 1KB, 1)
Write-Host "Built $OutFile ($kb KB) - syntax OK" -ForegroundColor Green
