#Requires -Version 5.1
<#
  build.ps1 - bundle src\ into a single dist\Sel01Tweaker.ps1 for one-liner use:
      & ([scriptblock]::Create((irm https://github.com/seltonmt012/Sel01-Tweaker/releases/latest/download/Sel01Tweaker.ps1))) -Profile Gaming

  Inserts lib + modules at the #__SEL01TWEAKER_BUNDLE_INSERT__ marker so the entry's
  param() block stays the first statement in the file.
#>
[CmdletBinding()]
param([string]$OutFile = (Join-Path $PSScriptRoot 'dist\Sel01Tweaker.ps1'))

$src    = Join-Path $PSScriptRoot 'src'
$marker = '#__SEL01TWEAKER_BUNDLE_INSERT__'

# Order: shared libs first, then numbered modules.
$parts = @(
    (Join-Path $src 'lib\Common.ps1'),
    (Join-Path $src 'lib\Backup.ps1'),
    (Join-Path $src 'lib\Ui.ps1')
) + (Get-ChildItem (Join-Path $src 'modules') -Filter '*.ps1' | Sort-Object Name | ForEach-Object FullName)

$bundle = [System.Text.StringBuilder]::new()
foreach ($p in $parts) {
    [void]$bundle.AppendLine("# ----- bundled: $(Split-Path $p -Leaf) -----")
    [void]$bundle.AppendLine((Get-Content -Path $p -Raw))
    [void]$bundle.AppendLine('')
}

$entry = Get-Content -Path (Join-Path $src 'Sel01Tweaker.ps1') -Raw
if (-not $entry.Contains($marker)) { throw "Marker $marker not found in src\Sel01Tweaker.ps1" }

$header = @"
# ============================================================================
#  Sel01Tweaker - bundled distribution (generated by build.ps1; do not edit by hand)
#  One-click Windows 11 debloat + performance optimizer.
#  Source: src\  |  Run: .\Sel01Tweaker.ps1 -Profile Gaming   (auto-elevates)
# ============================================================================
"@

$final = $entry.Replace($marker, ($header + "`r`n" + $bundle.ToString()))

$outDir = Split-Path $OutFile -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
# BOM-less UTF-8 is mandatory: `irm` hands the raw text (BOM included) to
# [scriptblock]::Create(), and a leading U+FEFF makes the parser reject the
# param() block ("Unexpected attribute 'CmdletBinding'"), killing the one-liner.
# Set-Content -Encoding UTF8 writes a BOM on Windows PowerShell 5.1, so don't.
[System.IO.File]::WriteAllText($OutFile, $final, [System.Text.UTF8Encoding]::new($false))

# Syntax-validate the generated file before declaring success.
$errors = $null
[void][System.Management.Automation.Language.Parser]::ParseFile($OutFile, [ref]$null, [ref]$errors)
if ($errors -and $errors.Count) {
    Write-Host "Bundle has syntax errors:" -ForegroundColor Red
    $errors | ForEach-Object { Write-Host "  $($_.Message) (line $($_.Extent.StartLineNumber))" -ForegroundColor Red }
    exit 1
}

# The bundle must stay pure ASCII. Without a BOM, Windows PowerShell 5.1 reads a
# non-ASCII file as ANSI and mangles it - so no umlauts / box-drawing chars in src.
$raw = [System.IO.File]::ReadAllText($OutFile)
$bad = [regex]::Matches($raw, '[^\x00-\x7F]')
if ($bad.Count) {
    $chars = ($bad | ForEach-Object { $_.Value } | Select-Object -Unique) -join ' '
    Write-Host "Bundle contains $($bad.Count) non-ASCII char(s): $chars" -ForegroundColor Red
    Write-Host "Replace them in src\ (e.g. [char]0x2588) - BOM-less UTF8 + 5.1 = mojibake." -ForegroundColor Red
    exit 1
}

# The one-liner path: parse the file text exactly like `irm | scriptblock::Create`.
try { [void][scriptblock]::Create($raw) }
catch {
    Write-Host "Bundle is not usable via [scriptblock]::Create(): $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

$kb = [math]::Round((Get-Item $OutFile).Length / 1KB, 1)
Write-Host "Built $OutFile ($kb KB) - syntax OK" -ForegroundColor Green
